//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by lunasol.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDS_VERSION                     102
#define IDD_LUNASOL_DIALOG              103
#define IDS_UPDATE_FAILED               103
#define IDD_ABOUTBOX1                   104
#define IDD_UPDATE_DOWNLOAD             104
#define IDS_UP_TO_DATE                  104
#define IDD_UPDATE                      105
#define IDS_FEEDBACK_URL                105
#define IDS_MOONPHASE_NEWMOON           106
#define IDS_MOONPHASE_WAXING_CRESCENT   107
#define IDS_MOONPHASE_FIRST_QUARTER     108
#define IDS_MOONPHASE_WAXING_GIBBOUS    109
#define IDS_MOONPHASE_FULLMOON          110
#define IDS_MOONPHASE_WANING_GIBBOUS    111
#define IDS_MOONPHASE_THIRD_QUARTER     112
#define IDS_MOONPHASE_WANING_CRESCENT   113
#define IDS_AFRICA                      114
#define IDS_ASIA                        115
#define IDS_EUROPE                      116
#define IDS_NORTH_AMERICA               117
#define IDS_SOUTH_AMERICA               118
#define IDS_OCEANIA                     119
#define IDS_TODAY                       120
#define IDS_DATE_LABEL                  121
#define IDS_TIMEZONE_LABEL              122
#define IDS_SUNRISE_LABEL               123
#define IDS_SUNSET_LABEL                124
#define IDS_MOONRISE_LABEL              125
#define IDS_MOONSET_LABEL               126
#define IDS_SUNNOON_LABEL               127
#define IDR_MAINFRAME                   128
#define IDS_MOONNOON_LABEL              128
#define IDB_BITMAP1                     129
#define IDB_BITMAP_BANNER               129
#define IDS_TWILIGHT                    129
#define IDS_ANDORRA                     130
#define IDS_TWLIGHT_ASTRONOMICAL        130
#define IDS_AUSTRIA                     131
#define IDS_TWLIGHT_NAUTICAL            131
#define IDS_FRANCE                      132
#define IDS_TWLIGHT_CIVIL               132
#define IDS_GERMANY                     133
#define IDS_DAYLENGTH                   133
#define IDS_GREAT_BRITAIN               134
#define IDS_MOON_VISIBILITY             134
#define IDS_ITALY                       135
#define IDS_MOON_PHASE                  135
#define IDS_NETHERLANDS                 136
#define IDS_NEXT_NEW_MOON               136
#define IDS_SPAIN                       137
#define IDS_NEXT_FULL_MOON              137
#define IDS_SWITZERLAND                 138
#define IDS_CONTINENT                   138
#define IDS_BELGIUM                     139
#define IDS_COUNTRY                     139
#define IDS_DENMARK                     140
#define IDS_STATE                       140
#define IDS_FINLAND                     141
#define IDS_STATE_GERMANY               141
#define IDS_GREECE                      142
#define IDS_STATE_USA                   142
#define IDS_ICELAND                     143
#define IDS_STATE_FRANCE                143
#define IDS_IRELAND                     144
#define IDS_LATITUDE                    144
#define IDS_LIECHTENSTEIN               145
#define IDS_LONGITUDE                   145
#define IDS_LUXEMBOURG                  146
#define IDS_ABOUT                       146
#define IDS_MALTA                       147
#define IDS_UPDATE_CHECK                147
#define IDS_NORWAY                      148
#define IDS_CITY                        148
#define IDS_PORTUGAL                    149
#define IDS_FEEDBACK                    149
#define IDS_SWEDEN                      150
#define IDS_ABOUT_TITLE                 150
#define IDS_ABOUT_CONTACT               151
#define IDS_ABOUT_IMAGE_SRC             152
#define IDS_ABOUT_ICONS                 153
#define IDS_ABOUT_LOCATION_SRC          154
#define IDS_UPDATE_DOWNLOADING          155
#define IDS_UPDATE_CONNECTING           156
#define IDS_UPDATE_DOWNLOADING_TITLE    157
#define IDS_UPDATE_TITLE                157
#define IDS_UPDATE_NOW                  158
#define IDS_UPDATE_INSTALLED_VERSION    159
#define IDS_UPDATE_NEW_VERSION          160
#define IDS_UPDATE_NEW_VERSION_AVAILABLE 161
#define IDS_ALTITUDE_LABEL              162
#define IDS_AZIMUTH                     163
#define IDS_AZIMUTH_LABEL               163
#define IDS_ICON_SOURCE                 164
#define IDS_CLOSE                       165
#define IDS_SUNDECLINATION_LABEL        166
#define IDS_TIMEEQUATION_LABEL          167
#define IDS_LUNASOLCAL_MOBILE           168
#define IDS_ITUNES_URL                  169
#define IDS_ANDROID_MARKET_URL          170
#define IDS_WP_MARKET_URL               171
#define IDB_BITMAP_MPH1                 172
#define IDB_BITMAP_MPH2                 173
#define IDB_BITMAP_MPH3                 174
#define IDB_BITMAP_MPH4                 175
#define IDB_BITMAP_MPH5                 176
#define IDB_BITMAP_MPH6                 177
#define IDB_BITMAP_MPH7                 178
#define IDB_BITMAP_MPH8                 179
#define IDS_USA_AL                      180
#define IDS_USA_AK                      181
#define IDS_USA_AZ                      182
#define IDS_USA_AR                      183
#define IDS_USA_CA                      184
#define IDS_USA_CO                      185
#define IDS_USA_CT                      186
#define IDS_USA_DE                      187
#define IDS_USA_FL                      188
#define IDS_USA_GA                      189
#define IDS_USA_HI                      190
#define IDS_USA_ID                      191
#define IDS_USA_IL                      192
#define IDS_USA_IN                      193
#define IDS_USA_IA                      194
#define IDS_USA_KS                      195
#define IDS_USA_KY                      196
#define IDS_USA_LA                      197
#define IDS_USA_ME                      198
#define IDS_USA_MD                      199
#define IDS_USA_MA                      200
#define IDS_USA_MN                      201
#define IDS_USA_MS                      202
#define IDS_USA_MO                      203
#define IDS_USA_MT                      204
#define IDS_USA_NE                      205
#define IDS_USA_NV                      206
#define IDS_USA_NH                      207
#define IDS_USA_NJ                      208
#define IDS_USA_NM                      209
#define IDS_USA_NY                      210
#define IDS_USA_NC                      211
#define IDS_USA_ND                      212
#define IDS_USA_OH                      213
#define IDS_USA_OK                      214
#define IDS_USA_OR                      215
#define IDS_USA_PA                      216
#define IDS_USA_RI                      217
#define IDS_USA_SC                      218
#define IDS_USA_SD                      219
#define IDS_USA_TN                      220
#define IDS_USA_TX                      221
#define IDS_USA_UT                      222
#define IDS_USA_VT                      223
#define IDS_USA_VA                      224
#define IDS_USA_WA                      225
#define IDS_USA_WV                      226
#define IDS_USA_WI                      227
#define IDS_USA_WY                      228
#define IDS_USA_DC                      281
#define IDS_USA_MI                      282
#define IDS_USA                         283
#define IDS_CANADA                      284
#define IDC_HYPERLINK                   285
#define IDB_BITMAP2                     288
#define IDB_BITMAP_SUN                  288
#define IDB_BITMAP_MPH_SH2              289
#define IDB_BITMAP_MPH_SH3              290
#define IDB_BITMAP_MPH_SH4              291
#define IDB_BITMAP_MPH_SH5              292
#define IDB_BITMAP_MPH_SH6              293
#define IDB_BITMAP_MPH_SH7              294
#define IDB_BITMAP_MPH_SH8              295
#define IDC_COMBO_CITY                  1000
#define IDC_COMBO_COUNTRY               1003
#define IDC_COMBO_STATE                 1004
#define IDC_EDIT_SUNRISE2               1005
#define IDC_COMBO_CONTINENT             1007
#define IDC_EDIT_LAT                    1011
#define IDC_EDIT_LAT2                   1012
#define IDC_BUTTON_ABOUT                1015
#define IDC_STATIC_PRODUCT_NAME         1016
#define IDC_STATIC_COPYRIGHT            1017
#define IDC_STATIC_PIC_MOON_PHASE       1018
#define IDC_STATIC_MOON_PHASE           1019
#define IDC_STATIC_PIC_SUN              1019
#define IDC_BUTTON_UPDATE_CHECK         1022
#define IDC_COMBO_TIME_ZONE             1023
#define IDC_STATIC_STATE                1024
#define IDC_STATIC_TIMEZONE             1025
#define IDC_STATIC_INSTALLED_VERSION    1026
#define IDC_STATIC_LATEST_VERSION       1027
#define IDC_BUTTON_FEEDBACK             1027
#define IDC_BUTTON1                     1028
#define IDC_BUTTON_PREV                 1028
#define IDC_PROGRESS                    1029
#define IDC_STATIC_PROGRESS             1030
#define IDC_DATETIMEPICKER              1035
#define IDC_STATIC_SUNRISE              1037
#define IDC_STATIC_SUNRISE_VALUE        1037
#define IDC_STATIC_SUNSET               1038
#define IDC_STATIC_SUNSET_VALUE         1038
#define IDC_STATIC_MOONRISE             1039
#define IDC_STATIC_MOONRISE_VALUE       1039
#define IDC_STATIC_MOONSET              1040
#define IDC_STATIC_MOONSET_VALUE        1040
#define IDC_STATIC_SUNNOON              1041
#define IDC_VALUE_SUN_NOON              1041
#define IDC_STATIC_DAYLENGTH            1042
#define IDC_VALUE_DAYLENGTH             1042
#define IDC_STATIC_SUNSET2              1043
#define IDC_VALUE_TWILIGHT_ASTRON_END   1043
#define IDC_STATIC_SUNSET3              1044
#define IDC_VALUE_TWILIGHT_NAUT_END     1044
#define IDC_STATIC_SUNSET4              1045
#define IDC_VALUE_TWILIGHT_CIVIL_END    1045
#define IDC_STATIC_SUNSET5              1046
#define IDC_VALUE_TWILIGHT_ASTRON_START 1046
#define IDC_STATIC_SUNSET6              1047
#define IDC_VALUE_TWILIGHT_NAUT_START   1047
#define IDC_STATIC_SUNSET7              1048
#define IDC_VALUE_TWILIGHT_CIVIL_START  1048
#define IDC_STATIC_LUNARNOON            1049
#define IDC_VALUE_MOON_NOON             1049
#define IDC_STATIC_MOONPHASE            1050
#define IDC_VALUE_MOON_PHASE            1050
#define IDC_STATIC_VISIBILITY           1051
#define IDC_VALUE_MOON_VISIBILITY       1051
#define IDC_STATIC_SUNRISE_LABEL        1052
#define IDC_STATIC_LUNARNOON2           1053
#define IDC_VALUE_NEXT_NEW_MOON         1053
#define IDC_STATIC_LUNARNOON3           1054
#define IDC_VALUE_NEXT_FULL_MOON        1054
#define IDC_STATIC_SUNSET_LABEL         1055
#define IDC_STATIC_MOONRISE_LABEL       1056
#define IDC_STATIC_MOONSET_LABEL        1057
#define IDC_BUTTON_NEXT                 1058
#define IDC_BUTTON_TODAY                1059
#define IDC_VALUE_LOCATION_SRC          1060
#define IDC_VALUE_SUN_DECL              1060
#define IDC_VALUE_ALTITUDE              1060
#define IDC_VALUE_SUN_DECLINATION       1060
#define IDC_LABEL_ICON_SRC              1061
#define IDC_VALUE_MOON_DECL             1061
#define IDC_VALUE_AZIMUTH               1061
#define IDC_VALUE_MOON_DECLINATION      1061
#define IDC_LABEL_CONTACT               1062
#define IDC_VALUE_TIME_EQUATION         1062
#define IDC_LABEL_IMAGE_SRC             1063
#define IDC_LABEL_LOCATION_SRC          1064
#define IDC_CONTACT_VALUE               1065
#define IDC_VALUE_IMAGE_SRC             1066
#define IDC_VALUE_ICON_SRC              1067
#define IDC_LABEL_MOON_DECL             1068
#define IDC_LABEL_MOON_NOON             1069
#define IDC_LABEL_MOON_PHASE            1070
#define IDC_LABEL_MOON_VISIBILITY       1071
#define IDC_LABEL_SUN_NOON              1072
#define IDC_LABEL_SUN_DECL              1073
#define IDC_LABEL_SUN_DECLINATION       1073
#define IDC_LABEL_DAYLENGTH             1074
#define IDC_LABEL_LUNASOLCAL_MOBILE     1075
#define IDC_LABEL_TWILIGHT_NAUT         1076
#define IDC_LABEL_TWILIGHT_CIVIL        1077
#define IDC_LABEL_NEXT_NEW_MOON         1078
#define IDC_LABEL_NEXT_FULL_MOON        1079
#define IDC_LABEL_TWILIGHT              1080
#define IDC_STATIC_COUNTRY              1081
#define IDC_STATIC_CITY                 1082
#define IDC_STATIC_CONTINENT            1083
#define IDC_STATIC_DATE_LABEL           1084
#define IDC_STATIC_TIMEZONE_LABEL       1085
#define IDC_STATIC_LATITUDE             1086
#define IDC_STATIC_LONGITUDE            1087
#define IDC_STATIC_NEW_VERSION          1088
#define IDC_LABEL_ALTITUDE              1088
#define IDC_LABEL_MOON_DECLINATION      1088
#define IDC_STATIC_VERSION_INSTALLED    1089
#define IDC_LABEL_TIME_EQUATION         1089
#define IDC_LABEL_SUNRISE_AZIMUTH       1090
#define IDC_VALUE_SUNRISE_AZIMUTH       1091
#define IDC_LABEL_AZIMUTH               1092
#define IDC_LABEL_SUNSET_AZIMUTH        1092
#define IDC_CLOSE_ABOUT                 1092
#define IDC_VALUE_SUNSET_AZIMUTH        1093
#define IDC_LABEL_MOONRISE_AZIMUTH      1094
#define IDC_VALUE_MOONRISE_AZIMUTH      1095
#define IDC_LABEL_MOONSET_AZIMUTH       1096
#define IDC_VALUE_SUNSET_AZIMUTH2       1097
#define IDC_VALUE_MOONSET_AZIMUTH       1097
#define IDC_BUTTON_IPHONE               1099
#define IDC_BUTTON_ANDROID              1100
#define IDC_BUTTON_WP                   1101
#define IDC_LABEL_TWILIGHT_CIVIL2       1103
#define IDC_LABEL_TWILIGHT_ASTRONOMICAL 1103
#define IDC_INSTALLED_VERSION           65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        296
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
